### ISSUE TITLE
Gate Lite not seeing local servers

### ISSUE THREAD

**Issue by joeyak** [minekube/gate#210]
I can't seem to get gate to see my mc servers.

config.yaml
```
config:
  lite:
    enabled: true
    routes:
      - host: mc.<URL>.com
        backend: localhost:25566
      - host: mc.secret.<URL>.com
        backend: localhost:25567
      # Testing to get it working at all
      - host: "*"
        backend: localhost:25566
```

I have a VPS (hosted in web) and a local server (on local network). Port 25565 is open from `web -> VPS -> local network` and I can access that. They're set up with docker, and I can connect to them on the local network using `192.x.x.x:25566` and `192.x.x.x:25567`

```
services:
  gate:
    image: ghcr.io/minekube/gate:latest
    container_name: gate
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./gate.yml:/config.yml
  mc-survival:
    image: itzg/minecraft-server
    ...
    ports:
      - 25566:25565
    ...
  mc-secret:
    image: itzg/minecraft-server
    ...
    ports:
      - 25567:25565
    ...
```

When I set mc-survival ports to `25565:25565` I can join and connect
