### ISSUE TITLE
newest version of gate (v0.31.1) having issues receiving proxyProtocol in Gate-to-Gate configuration

### ISSUE THREAD

**Issue by ddx0** [minekube/gate#222]
OS: `Debian GNU/Linux 12 (bookworm)`
Arch: `x86_64`
Kernel: `6.1.0-10-amd64`
Go version: `go1.20.6 linux/amd64`
Servers tested: `Vanilla 1.20.1`, `Forge 1.19.2`, `Fabric 1.19.2`

**How I stumbled upon the problem:**

Updated gate recently to v0.31.1, attempted a Gate-to-Gate configuration utilizing Gate-Lite, with proxyProtocol enabled between them. However, when using v0.31.1 on both, upstream proxy fails to communicate with the downstream proxy with the following error message:

`"error": "failed to decode status response: error reading packet frame: error reading varint: EOF"`

followed by:

`"error": "all backends failed"`

**Upstream config:**
```yaml
config:
  bind: X.X.X.X:25565
  proxyProtocol: false
  lite:
    enabled: true
    routes:
      - host: ["*"]
        backend: X.X.X.X:25565
        proxyProtocol: true
        cachePingTTL: "-1s"
```

**Downstream config:**
```yaml
config:
  bind: X.X.X.X:25565
  proxyProtocol: true
  lite:
    enabled: true
    routes:
      - host: ["*"]
        backend: X.X.X.X:25565
        proxyProtocol: false
        cachePingTTL: "-1s"
```

Some further testing yielded the following results:

1. Gate v0.31.1 -> Gate v0.31.1 (FAILS, newest to newest)
2. Gate v0.31.0 -> Gate v0.31.0 (SUCCEEDS, last version to last version)
3. Gate v0.31.0 -> Gate v0.31.1 (FAILS, last version to newest)
4. Gate v0.31.1 -> Gate v0.31.0 (SUCCEEDS, newest to last version)

From this, it appears the version of the upstream proxy does not seem to matter; however, if the downstream proxy is the newest version it will fail at the upstream proxy. It is interesting to note this seems to be a `proxyProtocol` issue, as disabling `proxyProtocol` on both the upstream and downstream proxies allows the latest version (v0.31.1) to be used successfully on both.

**How to reproduce:**

1. Download v0.31.1 (latest) and v0.31.0 (last) versions of the gate proxy on each machine.
2. Create a Gate-to-Gate configuration over Gate-Lite with `proxyProtocol` enabled between them.
3. Attempt connecting.

**Caveats:**
- Only tested on current Debian Stable/amd64 (Bookworm/12)
- Only tested using native Go binaries, and did not test with Docker or Kubernetes
- Only tested utilizing Lite-Mode
