### ISSUE TITLE
Lite mode: client showing "incompatible version" in servers list

### ISSUE THREAD

**Issue by amadeusmz** [minekube/gate#225]
config:
```
config:
  bind: 0.0.0.0:25564
  onlineMode: false
  lite:
    enabled: true
    routes:
      - host: '*'
        backend: '<backend>'
        proxyProtocol: true 
```
Client version: 1.19.2    
Image: The top one is expected behaviour (bungeecord & infraed proxy), the bottom one is gate's actual behaviour

![image](https://github.com/minekube/gate/assets/15067059/591600c4-b9ef-4b94-9fb8-85f2c16d8305)
