### ISSUE TITLE
bug: Unable to verify player details

### ISSUE THREAD

**Issue by Nelonn** [minekube/gate#232]
Any connect any paper-1.19.4-550 server fails with "Unable to verify player details"

Running gate from go module

gate config:
```
  onlineMode: false
  servers:
    auth_server: 127.0.0.1:26000
  try:
    - auth_server
  forwarding:
    # Options: legacy, none, velocity
    mode: velocity
    # The secret used if the mode is velocity.
    velocitySecret: todo_velocity_secret
```

paper config:
```
  velocity:
    enabled: true
    online-mode: false
    secret: todo_velocity_secret
```

gate logs:
```
2023-08-11T00:27:09.708+0300    INFO    java.client.player      proxy/switch.go:320     player disconnected from server while connecting        {"name": "Nelonn", "id": "c9088398-d4db-4fe5-99e1-0b19aa1383c9", "server": "auth_server", "reason": "Unable to verify player details"}
2023-08-11T00:27:09.708+0300    INFO    java.client.player      proxy/player.go:623     player has been disconnected    {"name": "Nelonn", "id": "c9088398-d4db-4fe5-99e1-0b19aa1383c9", "reason": "§cCan't connect to server \"auth_server\": Unable to verify player details"}
```

paper logs:
```
[00:27:09 INFO]: Disconnecting com.mojang.authlib.GameProfile@4ea00ac8[id=<null>,name=Nelonn,properties={},legacy=false] (/127.0.0.1:61129): Unable to verify player details
[00:27:09 INFO]: com.mojang.authlib.GameProfile@4ea00ac8[id=<null>,name=Nelonn,properties={},legacy=false] (/127.0.0.1:61129) lost connection: Unable to verify player details
```
