### ISSUE TITLE
feat(Lite): Allow configuring players in fallback status response

### ISSUE THREAD

**Issue by robinbraemer** [minekube/gate#281]
- requested by discord community

This misses players counts:

```yaml
        fallback:
          motd: |
            §cLocalhost server is offline.
            §eCheck back later!
          version:
            name: '§cTry again later!'
            protocol: -1
          # The optional favicon to show in the server list (optimal 64x64).
          # Accepts a path of an image file or the base64 data uri.
          favicon: xxxx
    ```
