### ISSUE TITLE
bug: Unable to join a heavly moded server (no matter the loader)

### ISSUE THREAD

**Issue by ajh123** [minekube/gate#322]
# Description of issue

When I connect to my Fabric server with `/server FabricCreative`  I get sent back to the lobby server. When using another proxy (Velocity) everything works correctly. I've also had similar problems with Connect.

I assume the problem comes from that Gate does not understand mods that use custom packets.

## Fabric server configurations

MC version : `1.20.1`
Fabric loader: `0.15.9`

### Mods

```
appliedenergistics2-fabric-15.1.0.jar
automobility-0.4.2+1.20.1-fabric.jar
cc-tweaked-1.20.1-fabric-1.110.2.jar
cloth-config-11.1.118-fabric.jar
create_enchantment_industry-1.2.16.jar
createaddition-fabric+1.20.1-1.2.3.jar
create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
crossstitch-0.1.6.jar
fabric-api-0.92.1+1.20.1.jar
FabricProxy-Lite-2.6.0.jar
'ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric(1).jar'
iCommon-Fabric-bundle.jar
luckperms/
LuckPerms-Fabric-5.4.102.jar
LuckPerms-Fabric-PlaceholderAPI-Hook.jar
midnightcontrols-1.8.2+1.20.jar
modmenu-7.2.2.jar
MTR-fabric-1.20-3.2.2-hotfix-1.jar
open-parties-and-claims-fabric-1.20.1-0.22.0.jar
replaymod-1.20.1-2.6.15.jar
Steam_Rails-1.6.0+fabric-mc1.20.1.jar
styled-chat-2.2.3+1.20.1.jar
vanilla-permissions-0.2.2+1.20.1.jar
worldedit-mod-7.2.15.jar
Xaeros_Minimap_24.0.3_Fabric_1.20.jar
XaerosWorldMap_1.38.1_Fabric_1.20.jar
```

### Docker compose (minified)

```yaml
version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - internal
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cSxbeBkEy2xZZa5ASUvz3xRjee2bKer6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: 
      - cache:/data
  proxy:
    image: ghcr.io/minekube/gate:latest
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - "./proxy/config.yml:/config.yml"
```

### config.yml

```yaml
config:
  bind: 0.0.0.0:25565
  servers:
    Lobby_1: lobby-1:25565
    FabricCreative: 10.0.0.12:25566
  try:
    - Lobby_1
  forwarding:
    mode: velocity
    velocitySecret: <redacted>
  debug: true
  status:
    # The message of the day in legacy '§' format or modern text component '{"text":"...", ...}' json.
    motd: |
      §bMiners Online
      §bVisit ➞ §fminersonline.uk
  shutdownReason: |
    §cMiners Online proxy is shutting down...
    Please reconnect in a moment!
```

## debug log

[debug_log.txt](https://github.com/minekube/gate/files/15013433/debug_log.txt)
