### ISSUE TITLE
[feature] detection of docker containers running servers

### ISSUE THREAD

**Issue by Merith-TK** [minekube/gate#325]
This would be an extra config titled `dockerSupport` and its just a bool

this would make gate locate docker containers tagged with `minekube.host` and `minekube.port`
if either `tag` is empty (`""` string), default to `container.Name` and port `25565`

and configure it as if it was 
```yml
config:
  servers:
    <minekube.host>: <container.name>:<minekube.port>
```
