### ISSUE TITLE
bug: Cannot use custom commands in a Minestom server

### ISSUE THREAD

**Issue by elSapitoWai** [minekube/gate#506]
## Description of issue
When I connect to the server the command I try to use `/gm`, the command I added, but nothing happens. When I join directly and not via gate the command is working as intended.

The command shows up in the chat as an option.

The minestom server can be found here: https://github.com/elSapitoWai/minestomserver 

My gate config:
```
config:
  bind: 0.0.0.0:25565
  servers:
    server1: 192.168.1.105:25567
  try:
    - server1
  onlineMode: false
  bungeePluginChannelEnabled: false
```

I don`t know if the hardware impacts on the problem but I am using a Raspberry Pi 4B.
