### ISSUE TITLE
bug: Backend servers using SRV records fail

### ISSUE THREAD

**Issue by Izzy-Irvine** [minekube/gate#532]
If I set the backend server in config.yml to a server that uses an SRV record, it fails to connect:
```yaml
config:
  lite:
    enabled: true
    routes:
      - host: '*'
        backend: minehut.gg
```
